### PR TITLE
added addr qr code, resolves #256

### LINKED ISSUE #256: QR Code
We should consider displaying account QR codes on the address and wallet pages, and serving the raw image over an api url, e.g. `https://explorer.gochain.io/api/qr/<addr>` (maybe an extension as well, if it makes sense to provide more than one of `.png`, `.svg`, etc.)

### PR DESCRIPTION
**Pull request by bergauz**

### CODE REVIEW

**Comment by jmank88** [comment]
Can you post screenshot of each page? Mobile too

**Comment by r-gochain** [comment]
image
image
image

**Comment by r-gochain** [comment]
@bergauz also please add to opened wallet page (you added to "create new wallet" page, but not to "open existing wallet" page)

**Comment by jmank88** [comment]
What about dropping the QR label and just putting the image next to the text address?

**Comment by bergauz** [comment]
Screenshot 2019-04-11 at 20 38 56
@jmank88 smth like this?

**Comment by jmank88** [comment]
Yeah that looks good. Does it collapse underneath the hex address when too narrow?

**Pull request merged**
